name: Build and Push Docker Image to GHCR

# TRIGGER: This workflow runs only when manually triggered from the Actions tab.
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag to push (e.g., latest, v1.0.1)'
        required: true
        default: 'latest'


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Log in to Docker Hub
      #    Uses secrets to avoid exposing credentials in the code.
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Set up Docker Buildx
      #    This is a required step for the build-push-action.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Build the Docker image and push it to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true 
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mvshows-addon:latest
